---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  changed_when: false
- name: Ensure nginx is installed.
  apt:
    name: nginx
    state: installed
- name: Copy nginx configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx